export interface BookingEmailData {
  name?: string | null;
  service?: string | null;
  date?: string | null;
  time?: string | null;
  phone?: string | null;
  email?: string | null;
  notes?: string | null;
  price?: string | number | null;
}

const escapeHtml = (value: unknown): string =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const row = (label: string, value: unknown) => `
  <tr>
    <td style="padding:12px 0;color:#756d68;font-size:13px;vertical-align:top;width:34%;">${escapeHtml(label)}</td>
    <td style="padding:12px 0;color:#2e2927;font-size:15px;vertical-align:top;font-weight:600;">${escapeHtml(value || 'Not provided')}</td>
  </tr>`;

export const renderBookingEmail = (booking: BookingEmailData): string => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New appointment request</title>
  </head>
  <body style="margin:0;background:#f7f3f0;color:#2e2927;font-family:Arial,Helvetica,sans-serif;">
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;">New appointment request from ${escapeHtml(booking.name || 'a client')}.</div>
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background:#f7f3f0;padding:24px 12px;">
      <tr><td align="center">
        <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;background:#ffffff;border:1px solid #e7ded8;">
          <tr><td style="padding:30px 32px 22px;background:#2e2927;color:#ffffff;">
            <p style="margin:0 0 8px;font-size:12px;letter-spacing:1.5px;text-transform:uppercase;color:#e7cfc2;">Nail Inspo Studio</p>
            <h1 style="margin:0;font-size:26px;line-height:1.25;font-weight:600;">New appointment request</h1>
          </td></tr>
          <tr><td style="padding:24px 32px 30px;">
            <p style="margin:0 0 16px;font-size:16px;line-height:1.5;">A client has submitted a new booking request.</p>
            <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;">
              ${row('Client', booking.name)}
              ${row('Service', booking.service)}
              ${row('Date', booking.date)}
              ${row('Time', booking.time)}
              ${row('Price', booking.price || 'To be confirmed')}
              ${row('Phone', booking.phone)}
              ${row('Email', booking.email)}
              ${row('Notes', booking.notes)}
            </table>
            <p style="margin:24px 0 0;padding-top:18px;border-top:1px solid #e7ded8;color:#756d68;font-size:12px;line-height:1.5;">This message was generated by the booking form. Reply to this email to contact the client.</p>
          </td></tr>
        </table>
      </td></tr>
    </table>
  </body>
</html>`;